### ISSUE TITLE
Release with proper versions

### ISSUE THREAD

**Issue by jnebeker** [RadiusNetworks/radius-rails#30]
Is there a reason that we just target this via git and don't release versions? Is that something we might want to do?

cc: @cupakromer @csexton @jnebeker because Im sure at least one of you will know the reasons.

_Originally posted by @benreyn in https://github.com/RadiusNetworks/kracken/issues/659#issuecomment-916269567_

**Comment by csexton** [comment]
Two reasons that I did that, not sure if @cupakromer ever needed to or if he was just living with my decisions. 

1. Compatibility between Rails versions. When working on rails major version upgrades I needed to make changes to the gem, and didn't want to break other apps that depended on it. 
2. Lazy. I could get it working by linking to git directly and never went back to release and update the projects.

I am all for proper versioning and releasing. Makes way more sense now that there are more than 2 people working on it.

The apps I would check/be concerned about:

- https://github.com/RadiusNetworks/kracken
- https://github.com/RadiusNetworks/iris
- https://github.com/RadiusNetworks/captain

**Comment by csexton** [comment]
> we can use to segment different Rails versions to avoid breaking apps and signaling something big may have changed - so take a moment before updating the gem in your app

This! We can always bump the major version number now to make it obvious there may be breaking changes to the other apps.

**Comment by benreyn** [comment]
Awesome! Ill add "Let's cut real releases of this gem" to my personal to-do list. ☑️

**Comment by jnebeker** [comment]
Fixed in #38
